import Head from 'next/head';
import { Inter } from 'next/font/google';
import { useState } from 'react';
import { Header } from '@/shared/header/header';
import { ListRoutes } from '@/components/list-routes/list-routes';
import { HeadingH1Default } from '@/shared/headings/heading-h1-default/ heading-h1-default';
import { DefaultButton } from '@/shared/buttons/default-btn/default-btn';
import { SignInForm } from '@/components/auth-form/components/sign-in-form';
import { Footer } from '@/shared/footer/footer';
import styles from './index.module.scss';

const inter = Inter({ subsets: ['latin'] });

const HomePage = () => {
  const [isFormVisible, setIsFormVisible] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.wrapper}>
          <ListRoutes extraClass={styles.routes} />
          <div className={styles.entry}>
            {isFormVisible ? (
              <SignInForm />
            ) : (
              <>
                <HeadingH1Default label="Привет!" />
                <DefaultButton
                  label="Войти"
                  onClick={() => setIsFormVisible(true)}
                />
              </>
            )}
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
};

export default HomePage;
